version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9

    branches:
        only:
          - master

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install now
          command: sudo npm i -g --unsafe-perm now@15.0.8

      - run:
          name: set secret
          command: |
             sed -ie "s/__client_id__/${CLIENT_ID}/g" ./credentials.json
             sed -ie "s/__project_id__/${PROJECT_ID}/g" ./credentials.json
             sed -ie "s/__client_secret__/${CLIENT_SECRET}/g" ./credentials.json
             sed -ie "s/__access_token__/${ACCESS_TOKEN}/g" ./token.json
             sed -ie "s;__refresh_token__;${REFRESH_TOKEN};g" ./token.json

      - run:
          name: deploy asap now!!
          command: |
            now --public -t ${ZEIT_TOKEN}
            now --public --target production -t ${ZEIT_TOKEN} && now alias -t ${ZEIT_TOKEN}
