version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9

    branches:
        only:
          - master

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install now
          command: sudo npm i -g --unsafe-perm now@11.4.6

      - run:
          name: deploy asap now!!
          command: |
            now shinjuku-lt/shinjuku-lt-backend --public -t ${ZEIT_TOKEN}
            now alias -t ${ZEIT_TOKEN}
